### PR TITLE
Added 'direction' attribute to choose clockwise or counterclockwise

### PR DESCRIPTION
**Pull request by donotor**
Added 'direction' optional attribute to choose clockwise or counterclockwise. Clockwise keeps being the default.

### CODE REVIEW

**Comment by stakach** [comment]
Looks good. Thanks for the solution!

**Comment by stakach** [comment]
Hmm seems a little off.. 

image

**Comment by stakach** [comment]
All good, worked it out. Thanks again - slightly modified how you indicate rotation. Will push a new release

**Comment by aroncal** [comment]
:+1:

**Pull request merged**
